<a href="https://colab.research.google.com/github/dhurai1085/python-analytics-portfolio/blob/main/online_retail_sales_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/dhurai1085/python-analytics-portfolio/refs/heads/main/raw_dataset/online_retail_sales_data.csv'
df= pd.read_csv(url)
df_copy = df.copy()
df_copy.head(10)

,OrderID,CustomerID,ProductName,Brand,Raw_Weight,Country,OrderDate,UnitPrice
0,REC-861088,6120,Perly,Perly,100 g,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300 g,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100g,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22 g,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230g,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40
5,REC-674324,6760,Шоколад 85% какаова маса,J. D. Gross,125g,"Austria,Belgium,Bulgaria,Estonia,Finland,Franc...",2024-09-08,19.16
6,REC-867660,8420,CRISTALINE Eau De Source 0.5L,Cristaline,500 ml,"Belgium,Côte d'Ivoire,France,Germany,Luxembour...",2024-10-10,3.64
7,REC-448132,9144,Henry’s,Henry's,42g,Maroc,2024-12-30,17.59
8,REC-202400,10397,Milk chocolate bar,NaN,150 g,"Algeria,Cameroon,France,Morocco,Spain",2024-08-04,11.08
9,REC-386572,13888,Organic 70% Dark Chocolate Bar,Green & Black's,90g,"France,Irlande,Suède,Royaume-Uni",2025-10-15,12.14

In [ ]:
df.shape

(3000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      3000 non-null   object
 1   CustomerID   3000 non-null   int64
 2   ProductName  2904 non-null   object
 3   Brand        2665 non-null   object
 4   Raw_Weight   2488 non-null   object
 5   Country      3000 non-null   object
 6   OrderDate    3000 non-null   object
 7   UnitPrice    2615 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 187.6+ KB

In [ ]:
df.dtypes

OrderID         object
CustomerID       int64
ProductName     object
Brand           object
Raw_Weight      object
Country         object
OrderDate       object
UnitPrice      float64
dtype: object

In [ ]:
df['Raw_Weight'].tail(20)

2980    184 g
2981    250 g
2982     269g
2983    150 g
2984     75 g
2985        3
2986    840 g
2987    190 g
2988     170g
2989     110g
2990     433g
2991    350 g
2992     100g
2993    150 g
2994      NaN
2995      NaN
2996    100 g
2997    200 g
2998      700
2999     160g
Name: Raw_Weight, dtype: object

In [ ]:
df['Raw_Weight'] = df['Raw_Weight'].str.extract('(\d+)')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1235/2626532195.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Raw_Weight'] = df['Raw_Weight'].str.extract('(\d+)')

In [ ]:
df['Raw_Weight'] = pd.to_numeric(df['Raw_Weight'],errors='coerce')

In [ ]:
df['Raw_Weight'].isnull().sum()

np.int64(514)

In [ ]:
df['Raw_Weight'].dtype

dtype('float64')

In [ ]:
df['Raw_Weight'] = df['Raw_Weight'].fillna(df['Raw_Weight'].median())
df['Raw_Weight'].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

OrderID          0
CustomerID       0
ProductName     96
Brand          335
Raw_Weight       0
Country          0
OrderDate        0
UnitPrice      385
dtype: int64

In [ ]:
df = df.dropna(subset=['ProductName'])

In [ ]:
df.loc[:,'Brand'] = df['Brand'].fillna('Unknown')

In [ ]:
df.loc[:,'UnitPrice'] = df['UnitPrice'].fillna(df['UnitPrice'].median())

In [ ]:
df.isnull().sum()

OrderID        0
CustomerID     0
ProductName    0
Brand          0
Raw_Weight     0
Country        0
OrderDate      0
UnitPrice      0
dtype: int64

In [ ]:
# checking for duplicates

df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns = df.columns.str.lower()
df.columns

Index(['orderid', 'customerid', 'productname', 'brand', 'raw_weight',
       'country', 'orderdate', 'unitprice'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    'orderid' : 'order_id',
    'customerid': 'customer_id',
    'productname': 'product_name',
    'orderdate' : 'order_date',
    'unitprice': 'unit_price'

})

In [ ]:
df.dtypes

order_id         object
customer_id       int64
product_name     object
brand            object
raw_weight      float64
country          object
order_date       object
unit_price      float64
dtype: object

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [ ]:
df.head()

,order_id,customer_id,product_name,brand,raw_weight,country,order_date,unit_price
0,REC-861088,6120,Perly,Perly,100.0,"Morocco,United States",2024-02-22,13.18
1,REC-900952,12550,Prince Goût Chocolat,LU,300.0,"Algeria,Belgium,France,French Polynesia,German...",2024-11-13,1.50
2,REC-595965,6705,Excellence Noir Prodigieux 90% Cacao,"Lindt EXCELLENCE,Lindt",100.0,"Argelia,Austria,Bélgica,Bulgaria,Canadá,Repúbl...",2025-02-02,12.99
3,REC-942653,8645,Tonik,عربي,22.0,Maroc,2024-12-11,14.82
4,REC-885998,14430,Sésame,Gerblé,230.0,"Belgium, Bulgaria, France, en:switzerland",2025-08-21,18.40

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2904 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2904 non-null   object
 1   customer_id   2904 non-null   int64
 2   product_name  2904 non-null   object
 3   brand         2904 non-null   object
 4   raw_weight    2904 non-null   float64
 5   country       2904 non-null   object
 6   order_date    2904 non-null   datetime64[ns]
 7   unit_price    2904 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 204.2+ KB

In [ ]:
df.isnull().sum()

order_id        0
customer_id     0
product_name    0
brand           0
raw_weight      0
country         0
order_date      0
unit_price      0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df.to_csv("/content/drive/MyDrive/DA-ANB13/Python/python-practice/Pandas/data_cleaning/Cleaned_datasets/cleaned_online_retail_data.csv", index=False)